# Exported from Render on 2025-11-12T20:12:09Z
version: "1"
projects:
- name: Fam-Hub
  environments:
  - name: Cachebank1
    services:
    - type: web
      name: -.AiH_armony.Legacy-1.i'$
      runtime: python
      repo: https://github.com/adamsjeramy/AiHarmony
      plan: free
      region: oregon
      buildCommand: pip install -r requirements.txt
      startCommand: gunicorn your_application.wsgi
      autoDeployTrigger: commit
      previews:
        generation: automatic
